language: cpp
compiler:
  - gcc
  - clang
dist: xenial
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get remove -y --auto-remove mysql-*
  - sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
  - sudo apt-get install -y libvtk6.2 libvtk6-dev python-vtk6
script:
  - mkdir build
  - cd build
  - cmake -DVTKBOOL_TESTING=ON -DVTKBOOL_COVERAGE=ON -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1
  - ctest
install:
  - sudo pip install codecov
after_success:
  - gcov ../testing/testing.cxx -i -o CMakeFiles/testing.dir/testing/
  - codecov
