#!/bin/bash

if ( [ $1 == "all" ] || [ $1 == "py" ] )
then
  cd tibra/tests
  python3 test_tibra.py
  cd ../..
fi

for file in TestExecutables/*
do
  if ( [ ! ${file: -3} == ".py" ] && ( [ $1 == "all" ] || [ $1 == "cpp" ]) )
  then
    ./"$file"
  fi
done

