#!/bin/bash

if ( [ $1 == "all" ] || [ $1 == "py" ] )
then
  python3 tibra/tests/test_tibra.py
fi

for file in TestExecutables/*
do
  if ( [ ! ${file: -3} == ".py" ] && ( [ $1 == "all" ] || [ $1 == "cpp" ]) )
  then
    ./"$file"
  fi
done

if ( [ $1 == "thingi10k" ] )
then
  ./TestExecutables/test_tibra_thingi10k -- all $2 5 50
  ./TestExecutables/test_tibra_thingi10k -- all $2 2 10
fi

