#!/bin/bash

cp src/tests/test_reduction_of_inner_ips.py TestExecutables
for file in TestExecutables/*
do
  if ( [ ${file: -3} == ".py" ] && ( [ $1 == "all" ] || [ $1 == "py" ]) )
  then
    python3 "$file"
  fi
done
for file in TestExecutables/*
do
  if ( [ ! ${file: -3} == ".py" ] && ( [ $1 == "all" ] || [ $1 == "cpp" ]) )
  then
    ./"$file"
  fi
done

